---
- name: Listen for ServiceNow change Implement and run remediation
  hosts: all
  sources:
    - servicenow.itsm.records:
        table: change_request
        interval: 10
        # Filter ONLY by assignment group; newest first to avoid the “oldest page first” trap
        sysparm_query: >
          assignment_group=91b12d5b53c72610a33138f0a0490e52^
          ORDERBYDESCsys_updated_on^ORDERBYDESCsys_id
        filters:
          - ansible.eda.json_filter:
          - ansible.eda.normalize_keys:
        # - If you need labels for logging only, uncomment the line below.
        # display_value: true
  rules:
    - name: Change moved to Implement
      # - ServiceNow 'state' is a choice-list; in many instances '-1' maps to the label 'Implement'.
      condition: event.state == '-1'
      action:
        debug:
          msg: |
            Implement detected:
            - number: {{ event.number }}
            - work_start: {{ event.work_start }}
