---
- name: Listen for ServiceNow change Implement and run remediation
  hosts: all
  sources:
    - servicenow.itsm.records:
        table: change_request
        interval: 10
        # Filter ONLY by assignment group; newest first to avoid the “oldest page first” trap
        sysparm_query: >
          assignment_group=91b12d5b53c72610a33138f0a0490e52^
          ORDERBYDESCsys_updated_on^ORDERBYDESCsys_id
        filters:
          - ansible.eda.json_filter:
          - ansible.eda.normalize_keys:
        # - If you need labels for logging only, uncomment the line below.
        # display_value: true
  rules:
    - name: Run corresponding remediation workflow
      # - ServiceNow 'state' is a choice-list; in many instances '-1' maps to 'Implement'.
      throttle:
        once_within: 10 minutes
        group_by_attributes:
          - sys_id
      condition: event.state == '-1'
      action:
        debug:
          msg: |
            on_change_implement event:
            - number: {{ event.number | default('') }}
            - sys_id: {{ event.sys_id | default('') }}
            - parent_incident_sys_id: {{ event.parent | default('') }}
            - implementation_plan (raw): {{ event.implementation_plan | default('') }}
            - implementation_plan.parsed: {{ (event.implementation_plan | default('') | from_json) if (event.implementation_plan is defined) else {} }}
