---
- name: Parse implementation plan and emit dispatch info
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    implementation_plan: ""
  tasks:
    - name: Ensure implementation_plan provided
      ansible.builtin.assert:
        that:
          - (implementation_plan | string | trim) != ''
        fail_msg: "implementation_plan is required"

    - name: Parse implementation plan JSON
      ansible.builtin.set_fact:
        implementation_plan: "{{ implementation_plan | from_json }}"

    - name: Emit parsed implementation plan for EDA
      ansible.builtin.set_stats:
        data:
          implementation_plan_json: "{{ implementation_plan }}"
        aggregate: false
